const SITE_NAME = "Daily Task Tool";

const DEFAULT_TITLE =
  "Daily Task Tool | Utilities for Everyday Tasks";

const SITE_DESCRIPTION =
  "A collection of simple and useful retro-themed utility tools, developer utilities, games, and productivity companions, built with Next.js and NES.css.";
const SEO_KEYWORDS = [
  "Daily Task Tool",
  "QR Code Generator",
  "Roll a Dice",
  "Dice Roller",
  "Random Number Generator",
  "Slot Machine",
  "Text to Speech",
  "Password Generator",
  "Unit Converter",
  "Focus Timer",
  "Pomodoro Timer",
  "Word Counter",
  "Character Counter",
  "Text Statistics",
  "Binary Translator",
  "Binary Converter",
  "Text to Binary",
  "Base64 Encoder",
  "Base64 Decoder",
  "Base64 Converter",
  "UUID Generator",
  "GUID Generator",
  "Random UUID",
  "v4 UUID",
  "URL Encoder",
  "URL Decoder",
  "Text Case Converter",
  "Uppercase Converter",
  "Lowercase Converter",
  "Tic Tac Toe",
  "Play Tic Tac Toe",
  "Magic 8-Ball",
  "Fortune Teller",
  "Coin Flipper",
  "Flip a Coin",
  "Coin Toss",
  "Heads or Tails",
  "Virtual Coin",
  "Rock Paper Scissors",
  "Play Rock Paper Scissors",
  "Random Joke",
  "Get a Joke",
  "Funny Jokes",
  "Memory Game",
  "Card Matching",
  "Guess the Number",
  "Number Guessing Game",
  "Reaction Time Test",
  "Reflex Test",
  "Visual Speed Test",
  "Retro Speed Typer",
  "Typing Speed Test",
  "Retro Typing Test",
  "WPM Test",
  "Coding Typing Test",
  "Keyboard Speed Test",
  "Utilities",
  "Productivity",
  "Next.js Tools",
  "Daily tasks",
  "Todo List",
  "Task Manager",
  "Morse Code Translator",
  "Morse Code",
  "Translate Morse Code",
  "Stopwatch",
  "Lap Timer",
  "Time Tracker",
  "Color Converter",
  "HEX to RGB",
  "RGB to HEX",
  "Color Picker",
  "Basic Calculator",
  "Calculator",
  "Retro Calculator",
  "BMI Calculator",
  "Body Mass Index",
  "Health",
  "Hash Generator",
  "SHA-256 Hash",
  "Cryptographic Hash",
  "SHA-512 Hash",
  "JWT Decoder",
  "JSON Web Token",
  "Decode JWT",
  "Percentage Calculator",
  "Calculate Percentage",
  "Percent Change",
  "Text Reverser",
  "Reverse Text",
  "Reverse Characters",
  "Reverse Words",
  "URL Parser",
  "Parse URL",
  "Query Parameters",
  "Text Diff Viewer",
  "Compare Text Online",
  "Diff Checker",
  "Code Compare",
  "Compare Two Texts",
  "File Diff Tool",
  "Number Base Converter",
  "Decimal to Binary",
  "Hex to Decimal",
  "Base Converter",
  "Octal Converter",
  "Developer Utilities",
  "RegEx Tester",
  "Regular Expression Tester",
  "RegEx Playground",
  "Match Regular Expressions",
  "Regex Debugger",
  "Retro Sprite Maker",
  "Pixel Art Creator",
  "Draw pixel art online",
  "CSS Box Shadow Pixel Art",
  "Export Sprite to PNG",
  "SVG Pixel Art Generator",
  "8-bit Game Sprite Maker",
  "Retro SFX Generator",
  "8-bit Sound Maker",
  "Chiptune Sound Effects",
  "Web Audio Synthesizer",
  "Generate Retro Sound Effects",
  "8-bit Audio WAV Exporter",
  "Download WAV Sound Effects",
  "Roman Numeral Converter",
  "Convert Roman Numerals",
  "Decimal to Roman",
  "Roman to Decimal",
  "URL Slug Generator",
  "Generate Slug",
  "SEO Slug",
  "Aspect Ratio",
  "Calculate Aspect Ratio",
  "Image Dimensions",
  "Tip Calculator",
  "Split Bill",
  "Calculate Tip",
  "Restaurant Tip",
  "CSS Flexbox Playground",
  "Flexbox Visualizer",
  "Learn CSS Flexbox",
  "Interactive Flexbox",
  "Flexbox Cheat Sheet",
  "CSS Layout Generator",
  "CSS Flexbox Generator",
  "BPM Tapper",
  "Calculate BPM",
  "Beats Per Minute",
  "Tap Tempo",
  "Image to Base64",
  "Base64 Image Encoder",
  "Data URI Converter",
  "Image Encoder",
  "Loan Calculator",
  "Mortgage Calculator",
  "Calculate Loan",
  "Interest Calculator",
  "Age Calculator",
  "Calculate Age",
  "Exact Age",
  "Date of Birth Calculator",
  "List Shuffler",
  "Randomize List",
  "Shuffle Text Lines",
  "Random List Generator",
  "HTML Entity Encoder",
  "HTML Decoder",
  "Encode HTML",
  "Escape HTML",
  "CSS Gradient Generator",
  "Background Gradient",
  "CSS Generator",
  "CSV to JSON Converter",
  "Convert CSV to JSON",
  "JSON Converter",
];


const OG_IMAGE = {
  url: "/opengraph-image.png",
  width: 1200,
  height: 630,
  alt: "Daily Task Tool Landing Page",
};

const ensureLeadingSlash = (path = "/") =>
  path.startsWith("/") ? path : `/${path}`;

export const normalizeHost = (host?: string) => {
  if (!host) return undefined;
  if (host.startsWith("http://") || host.startsWith("https://")) return host;
  return `https://${host}`;
};

export const getSiteUrl = () =>
  normalizeHost(process.env.NEXT_PUBLIC_SITE_URL) ?? "http://localhost:3000";

export const getMetadataBase = () => new URL(getSiteUrl());

export const buildCanonical = (path = "/") =>
  new URL(ensureLeadingSlash(path), getSiteUrl()).toString();

export { DEFAULT_TITLE, OG_IMAGE, SEO_KEYWORDS, SITE_DESCRIPTION, SITE_NAME };
